# Generated by Django 6.0.2 on 2026-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuggestionBox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General Suggestion'), ('academic', 'Academic Concern'), ('facilities', 'Facilities Improvement')], max_length=50, null=True),
        ),
    ]
