"""
Django settings for claribox project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k$kksfss%&cg3^efq8810)rlin&s4l6cqyy^7u-cr2rhsh)tme'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #my app
    'SuggestionBox',
    'dashboard',
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'claribox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'SuggestionBox', 'templates'),
                 os.path.join(BASE_DIR, 'dashboard', 'templates'),],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'claribox.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'dashboard', 'static'),
]


# Authentication Redirects
# This tells Django where to go after logging in or out
#LOGIN_REDIRECT_URL = 'admin_dashboard'
#LOGOUT_REDIRECT_URL = 'login'
#LOGIN_URL = 'login'




# Site ID is required by django-allauth
SITE_ID = 1

# Google OAuth2 Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'hd': 'std.must.ac.ug',  # university domain
        }
    }
}

# Ensure the email is captured
# Modern Django 6.0 / Allauth syntax
ACCOUNT_SIGNUP_FIELDS = ['email']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'none' 

# Google already verified the email


# Update your Authentication Redirects
LOGIN_REDIRECT_URL = '/submit/' # Redirect to suggestion form after Google Login
LOGOUT_REDIRECT_URL = 'welcome'

SOCIALACCOUNT_LOGIN_ON_GET = True


# Session lasts for 600 seconds (10 minutes) of inactivity
SESSION_COOKIE_AGE =300 

# Ensures the session is wiped if the student closes the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Ensures the session is saved/updated on every request so the 5 mins resets while they type
SESSION_SAVE_EVERY_REQUEST = True
# If the 10 mins are up, send them back to the Google Login, not the Admin
# Tells Django where to send people who are NOT logged in
LOGIN_URL = 'welcome'
# --- FINAL REDIRECT LOGIC ---
LOGIN_URL = '/accounts/google/login/'
LOGIN_REDIRECT_URL = '/submit/'
LOGOUT_REDIRECT_URL = 'welcome'
ACCOUNT_LOGOUT_REDIRECT_URL = 'welcome'
# This ensures that when a user is deleted/logged out, 
# the next person (or the same person) gets a fresh, working security token.

CSRF_USE_SESSIONS = False  
CSRF_COOKIE_HTTPONLY = False

# --- BYPASS UGLY INTERFACES & AUTOMATE LOGIN ---
SOCIALACCOUNT_AUTO_SIGNUP = True  # Bypasses the "Sign up" form page
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'

# If a record already exists for the email, just link and log in silently
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# This handles the "A user with that username already exists" error
# by generating a random username if there is a conflict
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'

# Trust local development for the security handshake
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
